##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
fabric:
  os: "darwin"   # use "darwin" for MacOS X, "windows" for Windows
  arch: "arm64" # other possible values: "386","arm64","arm","ppc64le","s390x"
